### PR TITLE
Fix for background color fill not targeting entire image

### PR DESCRIPTION
**Pull request by jayhenderson**
I ran into an issue when filling the background color on transparent images, which were also being cropped. The fill color was only targeting the upper left corner of the image.

Comparing `vue-croppie` with `croppie`, I noticed that the fill was targeting the `out` dimensions and not the `canvas` dimensions. Changing this reference fixed me issue.

### CODE REVIEW

**Comment by jofftiquez** [comment]
Hi @jayhenderson thanks for helping me, however you should edit the code from `src` and then rebuild the project, not the one in the `dist`. Thanks.

**Comment by jayhenderson** [comment]
This is my first time editing an npm package. I see now that the line of code I was trying to edit was being pulled in from `croppie 2.5.1`, but it is fixed on the `croppie` master branch. Is there a way to use `vue-croppie` with this updated code?

**Comment by jofftiquez** [comment]
@jayhenderson I understand. So you want to use `vue-croppie` along with `2.5.1` version of `croppie`?

**Comment by jofftiquez** [comment]
@jayhenderson if that's the case, then you can : 

1. cd to vue-croppie after installing it. Under `node_modules/vue-croppie`
2. Open and edit `vue-croppie`'s package.json, find croppie and update the version to the version that you want. 
3. Reinstall `croppie` under the same directory `node_modules/vue-cropppie` run `npm install croppie` 

**Note** 
This is just a temporary solution. I might update `vue-croppie` sometime this week to the latest version of `croppie`. I'll let you know here.

**Pull request closed without merging**
