### PR TITLE
Feature/update build process

### PR DESCRIPTION
**Pull request by dobromir-hristov**
This PR updates the build process from using Webpack to Bili (Rollup)

This introduces a breaking change as now users are supposed to import Croppie CSS styles manually for both Browser and Bundle usages.

Users can now however register VueCroppie locally if they want to.

PS: Please keep in mind there is an issue with Croppie with the latest merged PR so a fix is pending: https://github.com/Foliotek/Croppie/pull/617

### CODE REVIEW

**Comment by jofftiquez** [comment]
Hi @dobromir-hristov I will give time to review this thanks.

**Comment by dobromir-hristov** [comment]
I am using this in our production btw and it works alright. There is an issue however with the bundled version of Croppie, which is why I had to create a fork. The author still has not released a new version, as he just merged my fix, without building, so we cant even use the github repo directly.

**Comment by dobromir-hristov** [comment]
I will test with the latest croppie release tonight, and if it works, we can merge this in.

**Comment by jofftiquez** [comment]
Hello @dobromir-hristov great! Can you send the pr link to croppie maybe I can ask the author to release a new version since he already merged it. Did he merge it to master?

**Comment by jofftiquez** [comment]
Also @dobromir-hristov would you kindly remove the yarn.lock and the `dist` in this PR? I will build this on my end so I could also perform my testing.

**Comment by jofftiquez** [comment]
Sorry I've been busy these past weeks. Thank you for your efforts on making this plugin better.

**Comment by dobromir-hristov** [comment]
`yarn.lock` should stay, if we are to have consistent deps. The dist was left because thats how it was released up to now.

**Comment by dobromir-hristov** [comment]
https://github.com/Foliotek/Croppie/pull/617 this is the PR. Since then, they have made a 2.6.4 but not released on NPM. Very sloppy maintained library...

**Comment by jofftiquez** [comment]
Thanks @dobromir-hristov I will try to contact the author.

**Comment by dobromir-hristov** [comment]
I think we should do a major version bump, as there is a breaking change in the css. Otherwise ppl might have a bad time imho.

**Comment by jofftiquez** [comment]
@dobromir-hristov 2.0.0 maybe?

**Comment by dobromir-hristov** [comment]
Yes.

**Comment by jofftiquez** [comment]
@dobromir-hristov uploaded v2.0.1

**Pull request merged**
